manifest:
  remotes:
    - name: zmkfirmware
      url-repo: https://github.com/zmkfirmware/zmk
    - name: badjeff
      url-repo: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/manifest/zephyr/west.yml
    - name: zmk-paw3395-driver
      remote: badjeff
      revision: main
  self:
    path: config
